# Standard docker-copose setup to build Wordpress site with mysql database
version: "3.3"
    
services:
  db:
    image: mysql:8.0.26
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: solutions
      MYSQL_PASSWORD: slt_sEzR2P9ewrdXJK
      MYSQL_DATABASE: slt_wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:5.8.1-apache
    volumes:
      - ./src/plugins:/var/www/html/wp-content/plugins
      - ./src/themes:/var/www/html/wp-content/themes
      - ./src/uploads:/var/www/html/wp-content/uploads
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: solutions
      WORDPRESS_DB_PASSWORD: slt_sEzR2P9ewrdXJK
      WORDPRESS_DB_NAME: slt_wordpress
volumes:
  db_data: {}
  wordpress_data: {}